---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prowlarr
  namespace: argo-system
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: kubernetes
  sources:
    - repoURL: "https://github.com/skel84/home-ops.git"
      path: kubernetes/apps/downloads/prowlarr
      targetRevision: main
      ref: repo
    - repoURL: https://bjw-s-labs.github.io/helm-charts
      chart: app-template
      targetRevision: 4.0.1
      helm:
        releaseName: prowlarr
        valueFiles:
          - $repo/kubernetes/apps/downloads/prowlarr/values.yaml
  destination:
    name: in-cluster
    namespace: downloads
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
