---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spegel
  namespace: argo-system
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  project: kubernetes
  sources:
    - repoURL: "https://github.com/skel84/home-ops.git"
      path: kubernetes/apps/kube-system/spegel
      targetRevision: main
      ref: repo
    - repoURL: ghcr.io/spegel-org/helm-charts
      chart: spegel
      targetRevision: 0.1.1
      helm:
        releaseName: spegel
        valueFiles:
          - $repo/kubernetes/apps/kube-system/spegel/values.yaml
  destination:
    name: in-cluster
    namespace: kube-system
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
