[env]
_.python.venv = { path = "{{config_root}}/.venv", create = true }
KUBECONFIG = "{{config_root}}/kubeconfig"
SOPS_AGE_KEY_FILE = "{{config_root}}/age.key"
TALOSCONFIG = "{{config_root}}/talos/clusterconfig/talosconfig"
BOOTSTRAP_DIR = "{{config_root}}/bootstrap"
KUBERNETES_DIR = "{{config_root}}/kubernetes"
ROOT_DIR = "{{config_root}}"
SCRIPTS_DIR = "{{config_root}}/scripts"
TALOS_DIR = "{{config_root}}/talos"

[tasks.deps]
description = "Install Helm dependencies"
run = [
  "helm plugin list | grep -q 'secrets' && helm plugin update secrets || helm plugin install https://github.com/jkroepke/helm-secrets",
  "helm plugin list | grep -q 'diff' && helm plugin update diff || helm plugin install https://github.com/databus23/helm-diff"
]

[tools]
python = "3.14"
"pipx:makejinja" = "2.8.2"
"aqua:argoproj/argo-cd" = "2.14.7"
"aqua:budimanjojo/talhelper" = "3.0.24"
"aqua:cilium/cilium-cli" = "0.18.2"
"aqua:cli/cli" = "2.69.0"
"aqua:cloudflare/cloudflared" = "2025.2.1"
"aqua:cue-lang/cue" = "0.12.0"
"aqua:FiloSottile/age" = "1.2.1"
"aqua:getsops/sops" = "3.9.4"
"aqua:go-task/task" = "3.42.1"
"aqua:helm/helm" = "3.17.2"
"aqua:helmfile/helmfile" = "0.171.0"
"aqua:jqlang/jq" = "1.7.1"
"aqua:kubernetes-sigs/kustomize" = "5.6.0"
"aqua:kubernetes/kubectl" = "1.32.3"
"aqua:mikefarah/yq" = "4.45.1"
"aqua:siderolabs/talos" = "1.10.1"
"aqua:yannh/kubeconform" = "0.6.7"
"asdf:janpieper/asdf-ksops" = "4.4.0"
