---
apiVersion: v1
kind: Service
metadata:
  name: cirros-baseline-ssh
  namespace: kubevirt
  labels:
    app.kubernetes.io/name: cirros-baseline
    app.kubernetes.io/component: ssh
spec:
  type: LoadBalancer
  allocateLoadBalancerNodePorts: true
  selector:
    kubevirt.io/domain: cirros-baseline
  ports:
    - name: ssh
      protocol: TCP
      port: 22
      targetPort: 22
