---
apiVersion: v1
kind: Service
metadata:
  name: ubuntu-example-ssh
  namespace: kubevirt
  labels:
    app.kubernetes.io/name: ubuntu-example
    app.kubernetes.io/component: ssh
spec:
  type: LoadBalancer
  allocateLoadBalancerNodePorts: true
  selector:
    kubevirt.io/domain: ubuntu-example
  ports:
    - name: ssh
      protocol: TCP
      port: 22
      targetPort: 22
