---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-gateway
  namespace: argo-system
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  project: kubernetes
  sources:
    - repoURL: "https://github.com/skel84/home-ops.git"
      path: kubernetes/apps/network/k8s-gateway
      targetRevision: main
      ref: repo
    - repoURL: https://ori-edge.github.io/k8s_gateway
      chart: k8s-gateway
      targetRevision: 2.4.0
      helm:
        releaseName: k8s-gateway
        valueFiles:
          - $repo/kubernetes/apps/network/k8s-gateway/values.sops.yaml
  destination:
    name: in-cluster
    namespace: network
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
