---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/kubevirt-manager/kubevirt-manager/releases/download/v1.5.3/bundled-v1.5.3.yaml
  - ./ingress.yaml
patches:
  - path: ./kubevirt-manager-deployment-patch.yaml
